// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC04bbSEkJlZVX26Ud08YnbrCWoEHzwOOg',
    appId: '1:751817212564:web:a462046e4d9ec1e34cea81',
    messagingSenderId: '751817212564',
    projectId: 'aura-4ac14',
    authDomain: 'aura-4ac14.firebaseapp.com',
    databaseURL: 'https://aura-4ac14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-4ac14.appspot.com',
    measurementId: 'G-0PLP3QPBSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWJUenxXBDp8iVHTF0W6vX4-yUOjmbWM',
    appId: '1:751817212564:android:e6e40d8860e3a2cf4cea81',
    messagingSenderId: '751817212564',
    projectId: 'aura-4ac14',
    databaseURL: 'https://aura-4ac14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-4ac14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx8LRG1q3DQhGaaYCSXmLDdcJSgTpgh9Q',
    appId: '1:751817212564:ios:d85b75dfb3dc125d4cea81',
    messagingSenderId: '751817212564',
    projectId: 'aura-4ac14',
    databaseURL: 'https://aura-4ac14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-4ac14.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx8LRG1q3DQhGaaYCSXmLDdcJSgTpgh9Q',
    appId: '1:751817212564:ios:d85b75dfb3dc125d4cea81',
    messagingSenderId: '751817212564',
    projectId: 'aura-4ac14',
    databaseURL: 'https://aura-4ac14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-4ac14.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY83A6YoSIGdMA0SBa1GCitnneq2ToV8g',
    appId: '1:751817212564:web:cc36ee9646983ac24cea81',
    messagingSenderId: '751817212564',
    projectId: 'aura-4ac14',
    authDomain: 'aura-4ac14.firebaseapp.com',
    databaseURL: 'https://aura-4ac14-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-4ac14.appspot.com',
    measurementId: 'G-7T7DXEBQD5',
  );
}
